### PR TITLE
[#418] Android Gradle Plugin 7.2.0

### PR DESCRIPTION
**Pull request by ccjernigan**
In addition to the dependency update, there was one small new lint error to resolve.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Manual tests: Did you update the [manual tests](../blob/main/docs/testing/manual_testing) as appropriate? _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed._ Code Coverage can be run with: `./gradlew connectedCheck -PIS_COVERAGE_ENABLED=true`
- [ ] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes?
- [ ] Screenshots: Did you provide before and after UI screenshots in the description of this pull request?  _This is only applicable for changes that modify the UI._
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after changes and when possible, leave it in a better place._
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [x] Run the app: Did you run the app and try the changes? _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Review by HonzaR — COMMENTED** [review]
Unfortunately, I'm not able to make the project after these changes. 

My AS version: 
```
Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 28, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.5
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.toml.lang (0.2.155.4114-212), Statistic (4.1.10), com.godwin.json.parser (1.6), idea.plugin.protoeditor (212.5080.8), org.rust.lang (0.4.164.4409-212), org.intellij.plugins.markdown (212.5457.16), com.thoughtworks.gauge (212.4746.52), org.jetbrains.kotlin (212-1.6.21-release-334-AS5457.46), com.developerphil.adbidea (1.6.5)
```

It's failing in `build-convention` with this output:
```
Executing tasks: [:assemble, :testClasses] in project /Users/honza/Projects/secant-android-wallet/build-convention

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'build-convention'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.4.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-jdk8' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.5.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-jdk8' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.4.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.4.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-jdk7' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.5.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-jdk7' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.4.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.5.31}.
     Required by:
         project :
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31.
     Required by:
         project : > org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-jdk8' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib:1.5.31.
     Required by:
         project : > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31
         project : > org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31.
     Required by:
         project : > org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-jdk7' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'

   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31.
     Required by:
         project : > org.jetbrains.kotlin:kotlin-stdlib:1.5.31
      > Cannot find a version of 'org.jetbrains.kotlin:kotlin-stdlib-common' that satisfies the version constraints:
           Dependency path ':build-convention:unspecified' --> 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:2.1.7' (runtime) --> 'org.gradle.kotlin:gradle-kotlin-dsl-plugins:2.1.7' (runtimeElements) --> 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib:1.5.31' (runtime) --> 'org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31'
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.4.31}' because of the following reason: Pinned to the embedded Kotlin
           Constraint path ':build-convention:unspecified' --> 'org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.5.31}' because of the following reason: dependency was locked to version '1.5.31'
```

**Comment by ccjernigan** [comment]
> 

What happens if you run from the command line with an additional `--write-locks` and then look at any resulting git dirty state?

**Comment by HonzaR** [comment]
> --write-locks

Build it from cmd with `./gradlew assembleDebug --write-locks` succeeded.

**Comment by HonzaR** [comment]
> > --write-locks
> 
> Build it from cmd with `./gradlew assembleDebug --write-locks` succeeded with no warnings. And git reports no changes then.

**Comment by HonzaR** [comment]
I have an update on this. Now it seems it's happening on my current branch too, so it's probably related to my update AS to Chipmunk and not to your changes. Although I had some errors while I was building this PR branch, I thought it could be because of my older version of AS, so I updated and then this error came up.

**Comment by HonzaR** [comment]
Filed a new separate issue related to the `build-convention` task failure - https://github.com/zcash/secant-android-wallet/issues/420.

**Comment by HonzaR** [comment]
I've tried to run our tests locally, as I saw they failed on CI because of the timeout. There is probably a new requirement for our integration tests. `BackupIntegrationTest` and `OnboardingIntegrationTest` fail on all tests with:

```
java.lang.RuntimeException: Unable to resolve activity for: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=co.electriccoin.zcash.ui.test/co.electriccoin.zcash.ui.screen.onboarding.TestOnboardingActivity }
at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:399)
```

I have already tried to update our test Manifest with `intent-filter` but with no result.

**Comment by ccjernigan** [comment]
> I've tried to run our tests locally, as I saw they failed on CI because of the timeout. There is probably a new requirement for our integration tests. `BackupIntegrationTest` and `OnboardingIntegrationTest` fail on all tests with:
> 
> ```
> java.lang.RuntimeException: Unable to resolve activity for: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=co.electriccoin.zcash.ui.test/co.electriccoin.zcash.ui.screen.onboarding.TestOnboardingActivity }
> at androidx.test.core.app.InstrumentationActivityInvoker.startActivity(InstrumentationActivityInvoker.java:399)
> ```
> 
> I have already tried to update our test Manifest with `intent-filter` but with no result.

There's some kind of internal change in the AGP 7.2 plugin, so I renamed our test package name which seems to have resolved it.

**Review by HonzaR — APPROVED** [review]
Everything seems alright now.

**Pull request merged**
