### PR TITLE
[#416] Robo test blank screens

### PR DESCRIPTION
**Pull request by HonzaR**
- Solve also debouncing issue on screens navigation
- Implemented with extension function on NavHostController, which compares actual and final destinations

Closes https://github.com/zcash/secant-android-wallet/issues/416, https://github.com/zcash/secant-android-wallet/issues/214.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Manual tests: Did you update the [manual tests](../blob/main/docs/testing/manual_testing) as appropriate? _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed._ Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules.
- [ ] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes?
- [ ] Screenshots: Did you provide before and after UI screenshots in the description of this pull request?  _This is only applicable for changes that modify the UI._
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [ ] How is code coverage affected? _We encourage you to compare coverage before and after changes and when possible, leaving it in a better place._
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Comment by HonzaR** [comment]
@ccjernigan I've just checked the Firebase Robo results and it seems quite better to me, but I can still see those blank screens in the [results](https://console.firebase.google.com/u/4/project/android-firebase-b0cf1/testlab/histories/bh.61ab335878181908/matrices/6520777406783750175/executions/bs.fa328a4e8d93cab2) of Pixel 2 Virtual API Level 27 device. The second one - Pixel 2 Virtual API Level 30 ends up alright - without the blank screens. I've also played with the thought that it's caused only by the slowness of the device and the screenshots are  taken before the it's laid out, but according to the [video](https://console.firebase.google.com/u/4/project/android-firebase-b0cf1/testlab/histories/bh.61ab335878181908/matrices/6520777406783750175/executions/bs.fa328a4e8d93cab2/videos) the screens really stay blank, unfortunately. Do you have any thoughts on this?

**Comment by ccjernigan** [comment]
> 

For the occasional remaining blank screen, my current guess is the `popBackStack()`.  If it gets called twice, we could end up with an empty back stack.  A better solution is probably to replace those with explicit `navigateJustOnce()` calls.

I'm not 100% sure what causes the long lag, but it appears to be triggered from the configuration change (language and uimode).  I noticed it when I was implementing the multi-language screenshots so it is not a regression with this PR.  For end-users, configuration changes will happen through a different mechanism so I don't think they'll see it happen the same it.  It might be worth filing an issue to follow up on.

**Comment by HonzaR** [comment]
Now, it seems like it gives us much better results. Even thought, the Robo tab says: 
```
Robo crawl encountered one screen with non-Android UI widgets, sampled below. Consider using game loops to test them more effectively.
MainActivity-9
```
I can't see any blank screens in the Robo chart, Screenshots, or in Video. So I believe it's fixed now.

**Review by ccjernigan — APPROVED** [review]
This is a great improvement!

**Pull request merged**
