### PR TITLE
Modify invisible filled-arrowback icon with twotone-arrowback on profile screen

### LINKED ISSUE #244: Back button is invisible on profile screen
### Describe the issue
When using the light theme, the back button in the action bar is not visible

#### If so, please list the steps to reproduce below:
1. After creating a wallet, tap on the profile screen
2. Verify Android is in light mode
3. Look for the back arrow in the top of the action bar left of the word profile

### Expected behavior
Button should be visible

### Actual behavior + errors

Button is nearly invisible

### PR DESCRIPTION
**Pull request by luckytokidoki**
fix #244

Does this violate your design guide? Also, should we change all arrow-back icons in other screens? I believe there is no need to do it since the icons are similar. Still not sure why the default filled icon did not show up. 😅

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Manual tests: Did you update the [manual tests](../blob/main/docs/testing/manual_testing) as appropriate? _While we aim for automated testing of the application, some aspects require manual testing. If you had to manually test something during development of this pull request, write those steps down._
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed._
- [ ] Documentation: Did you update documentation as appropriate? (e.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes?
- [x] Screenshots: Did you provide before and after UI screenshots in the description of this pull request?  _This is only applicable for changes that modify the UI._
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
secant-issue_244

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage before and after your changes and when possible, leave it in a better place._
- [ ] Documentation: Did you review Docs, [README.md](../blob/main/README.md), and [Architecture.md](../blob/main/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? _While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Review by ccjernigan — COMMENTED** [review]
Thank you for this pull request.  Although a small bug, it is important since it makes the initial skeleton of the app hard to navigate.

To answer your specific questions: 
 - While we have solid designs from our designer, we don't have a strong style guide implemented yet.  That is planned, although I need to file an issue for it.  It will be prioritized some time after we finish getting the (ugly) skeleton of the app in place.
 - We probably don't want to introduce an inconsistency by using twotone only here; that'll probably come back to bite us later.

I'm concerned that we don't know the root cause, and I'd like to find the root cause before deciding to switch to the twotone icon style.

The places where I think this bug might originate are:
 - Some `SmallTopAppBars` have a `tint = MaterialTheme.colorScheme.secondary` set, while others do not.  This inconsistency is probably a bug.
 - Something could be missing in the theme definition in `ui-design-lib`.  I think this issue started as a regression with the switch to Material3.  The design prior to the Material3 migration is not necessarily "ground truth", as we don't have a style guide in place yet.  #245 could possibly be a related issue, especially if there's something wrong in the theme definition

Do you want to look at those two bullet points to see if those help us find the root cause?

**Comment by luckytokidoki** [comment]
Yes, I can help checking the root cause. No promises but I'll give an update before Monday.

**Comment by luckytokidoki** [comment]
Update: I tried looking into the `ui-design-lib` but couldn't find anything out of ordinary. The debugging is also complicated because what's shown on the automated @preview is different from what's shown on the built app in the emulator.

**Comment by ccjernigan** [comment]
This has been implemented in #357

**Pull request closed without merging**
